### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by xxxcrow** [unixabg/cryptmypi#60]
Hi, great project, although I couldn't manage get it working 😁
Not sure if it's still working, and want to know if I should continue trying to set it up and use it the future 🫡

**Comment by gemesa** [comment]
Should be working, I have been using it for years. What is your issue?

**Comment by xxxcrow** [comment]
@gemesa nice to hear!
I think my last issue was #56, but adding the timeout doesn't do anything (probably I need to rebuild initramfs)(or it's even better to just edit the script)

Also, from minor issues, the WiFi is not always working, and also the build time is pretty long 😅

**Comment by unixabg** [comment]
@xxxcrow yes alive.

On changing time rebuild initramfs. Marking completed for this topic.
